### ISSUE TITLE
Error "Invalid SSAS Server"

### ISSUE THREAD

**Issue by danyocean** [DrJohnT/DeployCube#2]
Hi, 
Trying to use you Publish-Cube command with psexec, give me this error "Invalid SSAS Server" with the right name of destination SSAS server.

There is my powershell script

`param (
    [Parameter(Position=0,Mandatory=$true)]
    [string]$cubename,
    [Parameter(Position=1,Mandatory=$true)]
    [string]$cubenameprod,
    [Parameter(Position=2,Mandatory=$true)]
    [string]$dest
)
$cubenamefull=Get-ChildItem -Path D: -Include *.asdatabase -recurse -File -Name | Select-String -pattern "bin" | Select-String -pattern $cubename
$cubefullpath="D:\"+$cubenamefull
copy $cubefullpath $cubefullpath-ori
(Get-Content $cubefullpath) | ForEach-Object {$_ -replace 'lolo','loulou'} | Out-File $cubefullpath
Publish-Cube -asDatabasePath $cubefullpath -Server $dest -CubeDatabase $cubenameprod
copy $cubefullpath-ori $cubefullpath
rm $cubefullpath-ori`

Can you help me around this problem please?

**Comment by DrJohnT** [comment]
Please retry with latest version 1.2

**Comment by jabteles** [comment]
> Please retry with latest version 1.2

This is still not available (https://marketplace.visualstudio.com/items?itemName=avdbrink.VSTS-SSAS) will you upload?

**Comment by DrJohnT** [comment]
@jabteles 
SSAS Build & Deploy is not my extension.  My extension is [SSAS Tabular Cube Deployment Tools](https://marketplace.visualstudio.com/items?itemName=DrJohnExtensions.DeployTabularModel) which has been updated with the latest DeployCube codebase
