### ISSUE TITLE
Deploy database DACPAC using a DAC Publish Profile failure

### ISSUE THREAD

**Issue by jaydsoni** [DrJohnT/DeployCube#4]
Hi, we use this task to deploy database schema. This started failing recently with the following error,

2021-01-11T21:10:49.7014850Z ##[error]Error: Cannot validate argument on parameter 'Version'. The argument "" does not belong to the set "150,140,130,120,110,15,14,13,12,11" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

I confirmed that the sqlpackage.exe is on the deployment server. Please help us identify the actual issue and resolving it.

Thank you.

**Comment by jaydsoni** [comment]
It started working for some reason.

**Comment by DrJohnT** [comment]
@jaydsoni 
As I mentioned, I release a new version of the extension.  I suspect that you simply need to edit the pipeline to get the new version to be installed on your build server.

**Comment by contemilw** [comment]
I am still having this issue with the pipeline release task 'Publish DACPAC using a DAC Publish Profile' version 1.2.9.

[error]Publish-DacPac Error: Cannot validate argument on parameter 'Version'. The argument "" does not belong to the set "150,140,130,120,110,15,14,13,12,11" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

In the release task, Advance Options - SqlPackage.exe Version, I tried 'Latest' or 'SQL Server 2017', and both have the same error. (Our DB server is using SQL Server 2017.)

Can you please help with it? Thanks!
